### ISSUE TITLE
Test Data

### ISSUE THREAD

**Issue by MoritzSkowronski** [keijiro/Bibcam#10]
Hi,

do you have a test recording by any chance so we can play around with the decoding without actually having a LIDAR enabled device at home? That would be great!

**Comment by keijiro** [comment]
I wanted to share one but didn't due to public privacy concern. I'd like to record another one that is safe for sharing.

**Comment by MoritzSkowronski** [comment]
Ah, that makes sense and thanks for the quick answer!

**Comment by Drumaddict182** [comment]
Hi Moritz, i have recorded some tests footage with an iPhone 12 pro. It works great. I can share it with you if you want.

**Comment by MoritzSkowronski** [comment]
Hey, thanks for trying to help! :) In the meantime, I've recorded my own test videos. Thanks @keijiro for the great and impressive work!

**Comment by timrumpf** [comment]
Hi Moritz, Hi Drumaddict182,
would it be possible for you to share one of the test videos?

**Comment by Drumaddict182** [comment]
Hi @TimSBB, here we go : https://drive.google.com/file/d/1rnELGD4bUr-DdGZ6venjEMsrHf9hByLf/view?usp=sharing
But it is very stupid test videos. Have fun

**Comment by timrumpf** [comment]
@Drumaddict182 Awesome! Thank you!

**Comment by kosowski** [comment]
Hi @Drumaddict182 , the file is not longer available, would it be  possible to re upload it, please? Thanks anyway!
