### ISSUE TITLE
Keep getting error when building to iOS

### ISSUE THREAD

**Issue by dariusjulian** [keijiro/Bibcam#12]
I keep getting the error

Unhandled Exception:  System.ArgumentException: Unknown runtime profile : unityaot-macos  Available profiles were: legacyunity, net20, net45, unityaot, unitydots, unityjit

Any idea on how to resolve this?

Thank you in advance!

**Comment by keijiro** [comment]
It seems like your Unity Editor installation is broken. Which version are you using? Does it work with an empty iOS project? Could you try another version of Unity?

**Comment by dariusjulian** [comment]
Apologies for the delay.  The issue was on my end.  I was using a very old version of Xcode. I have updated to the latest version am able to build the app.  When I do, the app screen has lines going diagonally and the log says 
"No active UnityEngine.XR.ARSubsystems.XRCameraSubsystem is available".  It says the same thing about XRSessionSubsystems and XROcclusionSubsystems.  

Any ideas what that could be?

I am using the Build Profile in the project called iOS Encoder App
I'm using:
Xcode: 16.1
Unity: 6000.0.29f1
Mac: Sonoma 14.6

Any help would be appreciated.  I feel like I've almost got it able to run.  Thank you in advance!

**Comment by keijiro** [comment]
Which iPhone model are you using with the project?

**Comment by dariusjulian** [comment]
Its an iPhone 15 pro with iOS 18.1.

**Comment by keijiro** [comment]
Thanks. Then, could you try the ARFoundation Samples with the device? If it works, Metavido should work too.
https://github.com/Unity-Technologies/arfoundation-samples

**Comment by dariusjulian** [comment]
They should work as it's only one generation behind the newest iPhone. I've also used this device for other AR apps with no issues.  I wonder if for some reason ARKit isn't being included or loaded in the build.  I will try the AR Foundation samples and will report back.

**Comment by dariusjulian** [comment]
I think I figured it out.
It seems in newer versions of XR, I need to call "LoaderUtility.Initialize();".
It seems to be building out and working now.  Thank you for you assistance!

**Comment by keijiro** [comment]
I don’t think that is necessary for the latest version of AR Foundation, but I’ll revisit it if I encounter the same issue in future updates. Thanks for confirming.
