### ISSUE TITLE
Work wit URP?

### ISSUE THREAD

**Issue by SashaBes** [keijiro/Bibcam#2]
Hello, your project is just amazing. Is there any way I can get it to work wit URP? When I change to it, the video is not displaying anymore

**Comment by keijiro** [comment]
I made the BibcamVfx project for HDRP, and I'll make another project for URP.

**Comment by SashaBes** [comment]
> I made the BibcamVfx project for HDRP, and I'll make another project for URP.

These are the best news!!! I spent the whole day trying to adjust it but I just cannot get it to work

**Comment by keijiro** [comment]
I implemented it in the following repository: https://github.com/keijiro/BibcamUrp

**Comment by SashaBes** [comment]
> I implemented it in the following repository: https://github.com/keijiro/BibcamUrp

Incredible! Will it also work with VFX Graph like in your BibcamVfx HDRPproject?

**Comment by keijiro** [comment]
> Will it also work with VFX Graph like in your BibcamVfx HDRPproject?

It should work without any extra modification.

**Comment by SashaBes** [comment]
> > Will it also work with VFX Graph like in your BibcamVfx HDRPproject?
> 
> It should work without any extra modification.

When I try to implement you VF Voxels from HDRP in the URP project, it just shoots the particles from one point. VFX Property Binder is added, Decoder and Demuxer slots are set. Do you know what could be the problem?

**Comment by keijiro** [comment]
Did you copy subgraphs too?

**Comment by SashaBes** [comment]
> Did you copy subgraphs too?

I copied Bibcam Sample Random subgraph (also used in the Voxel effect), and I also copied Bibcam Sample UV and Bibcam Depth To World Operator, but I don't see how it is used in the effect. There are also no empty subgraphs or operators in the effect after copying

**Comment by keijiro** [comment]
Did you import the `jp.keijiro.vfxgraphassets` package?

**Comment by SashaBes** [comment]
> Did you import the `jp.keijiro.vfxgraphassets` package?

Yes, I added it to the manifest and packages-lock.json files and I can see it in the packages folder in the project

**Comment by keijiro** [comment]
Then I think it should work. I'll try it on my side later.

**Comment by SashaBes** [comment]
> Then I think it should work. I'll try it on my side later.

Also the effect properties like RayParams are changing in play mode, the Color and DepthMap appear, so it looks like it is working, but it doesn't affect the particles for some reason. Thank you very much for looking into it later.

**Comment by keijiro** [comment]
I added a VFX graph sample to the BibcamUrp repository and verified it works correctly.

I'm not sure about Voxels.vfx, but it should work too.

**Comment by SashaBes** [comment]
> I added a VFX graph sample to the BibcamUrp repository and verified it works correctly.
> 
> I'm not sure about Voxels.vfx, but it should work too.

Now it works perfectly, thank you very much!
