### ISSUE TITLE
"striped screen"

### ISSUE THREAD

**Issue by thePostFuturist** [keijiro/Bibcam#3]
Compiled from Unity 2021.2.3f1 running on iOS 15.0.2 iPhone 13 Pro. Getting a striped screen, borders turned red when I press record. Test.mp4 video fails to play in decoder: 
`WindowsVideoMedia error unhandled Color Standard: 0  falling back to default this may result in rendering issues`

**Comment by keijiro** [comment]
Did you approve the camera access request from the app? Please check if Bibcam is allowed to access the camera in System Settings.

> Test.mp4 video fails to play in decoder:
> WindowsVideoMedia error unhandled Color Standard: 0 falling back to default this may result in rendering issues

If you're trying to use the recorded video on Windows, you can ignore this warning message. You can play it back without any issue in most cases.

**Comment by thePostFuturist** [comment]
That’s a good clue, it never asks for permission. Nothing changed in my
build besides bundle.

**Comment by keijiro** [comment]
Could you try re-enabling it from System Settings?

**Comment by thePostFuturist** [comment]
it is actually not even listed in settings. I figured it out though -- for some reason you have your Camera disabled. Enabling it allows recording.
