### ISSUE TITLE
Works with lidar or realsense devices ? 

### ISSUE THREAD

**Issue by Drumaddict182** [keijiro/Bibcam#5]
Hi Keijiro, once again it's an amazing project. Any chance to see this app works with any other lidar or Realsense devices ? I don't have an IPhone 13 Max. Or is there a way to synchronize tracking data with a video clip recorded with a lidar or realsense devices. 

Arigato gozaimasu.

**Comment by keijiro** [comment]
I implemented Bibcam because iOS ARKit provides camera tracking data.

There is no official implementation of camera tracking (VSLAM) for RealSense.

If you know a RGBD camera system with camera tracking capability, please let me know it. I'd like to consider porting Bibcam  to it.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by ianchase09** [comment]
this would be worth porting , has a unity package too
https://store.stereolabs.com/products/zed-2i

would love it on urp too :)

**Comment by keijiro** [comment]
@ianchase09 Is there any VSLAM for this device?

I can't find any one, so the situation is the same to RealSense.
