### ISSUE TITLE
No communication with Camera

### ISSUE THREAD

**Issue by nfabula** [keijiro/Bibcam#8]
Hi,
_I love this project, thanks tos for sharing with the world._ 
Noob here. I can't manage to capture any video on my device. It looks like there's simply no communication with iPhone's camera. I don't see any preview (only stripes) and even if I hit record, nothing is saved on device.
Unity Remote 5 has camera access in iOS settings.

<img width="594" alt="Screen Shot 2021-12-10 at 09 35 03" src="https://user-images.githubusercontent.com/3941818/145617119-10d0bec5-191e-41ec-bc6a-feff4ace213f.png">

I'm using Unity 2021.2.5f1 Personal on a MBP 16" with MacOS Big Sur. 
iPhone 13 Pro Max, iOS 15.1.1 (I tried both "Any iOS device" or "iPhone 13 Pro" in Project Settings / Editor)

<img width="873" alt="Screen Shot 2021-12-10 at 09 28 27" src="https://user-images.githubusercontent.com/3941818/145616872-d37d0300-337e-4ddc-ad3f-855311ae0cbf.png">

Am I missing something ?

<img width="2672" alt="Screen Shot 2021-12-10 at 09 29 06" src="https://user-images.githubusercontent.com/3941818/145616860-73ef6c4a-7fc6-4595-aefa-e56b7fe164cf.png">
<img width="1298" alt="Screen Shot 2021-12-10 at 09 33 49" src="https://user-images.githubusercontent.com/3941818/145616987-b10c8ea3-4f4d-4459-b90d-d7184e7e7e80.png">
<img width="1156" alt="Screen Shot 2021-12-10 at 09 29 23" src="https://user-images.githubusercontent.com/3941818/145616850-d68bd525-c5ef-4e25-a2af-3ed07333c3ef.png">

**Comment by keijiro** [comment]
It doesn't support Unity Remote. Try building the app and run it on the device.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
