### ISSUE TITLE
Only run on iOS??

### ISSUE THREAD

**Issue by Jiny530** [keijiro/Bibcam#9]
Hi, I am interested in your project.
And I wonder, does this only work on iOS? I mean, can't it run on Android device with ToF?

Thank you.

**Comment by keijiro** [comment]
It can't because ARCore on Android doesn't support depth sensor (it only support depth inference, and it's not practical for this usage).

Just out of curiosity, is there any Android device with ToF? I'd like to take it into consideration if there is any good one.

**Comment by Jiny530** [comment]
Thank you for the answer. It's a pity I only have Android.

The device with ToF that I know are the Galaxy S20 Ultra and S20+
But unlike Apple, it uses indirect ToF (I don't know well) so the performance is not good compared to iOS using Lidar.

**Comment by keijiro** [comment]
Thanks for the information.

I'm closing this issue as there is no plan for porting Bibcam to other platforms at the moment. Please feel free to reopen it for further problems.
